--DROP TABLE TBL_AA_DELEGATED_RESOURCES;
--DROP TABLE TBL_AA_SUBJECT2DELEGATOR;

--DROP TABLE TBL_AA_GROUP_ADMIN;
--DROP TABLE TBL_AA_USER_SESSION_INFO;
--DROP TABLE TBL_AA_SUBJECT2GROUP;
--DROP TABLE TBL_AA_SUBJECT2RES;
--DROP TABLE TBL_AA_GROUP2RES;

--DROP TABLE TBL_AA_AUTH2GROUP;
--DROP TABLE TBL_AA_AUTHORITY;

--DROP TABLE TBL_AA_RES2RES;
--DROP TABLE TBL_AA_RESOURCES;
--DROP TABLE TBL_AA_GROUP;
--DROP TABLE TBL_AA_SUBJECT_LOGIN;
--DROP TABLE TBL_AA_SUBJECT_PWD_HISTORY;
--DROP TABLE TBL_AA_PUBLIC_REG;

--DROP TABLE TBL_AA_SUBJECT ;

--DROP TABLE TBL_AA_APP_PARAM;
--DROP TABLE TBL_AA_APP;

--DROP TABLE TBL_AA_LOGIN_LOG;
--DROP TABLE TBL_AA_SIGN_LOG;

--DROP TABLE TBL_AA_RSA;


CREATE TABLE TBL_AA_APP	(
APP_ID	    VARCHAR(32)	NOT NULL,
APP_CODE	  VARCHAR(32)	NOT NULL,
APP_NAME	  VARCHAR(50)	NOT NULL,
APP_DESC	  VARCHAR(255)	,
CREATED_DT	TIMESTAMP	  NOT NULL,
CREATED_BY	VARCHAR(32) NOT NULL,
UPDATED_DT	TIMESTAMP	    ,
UPDATED_BY	VARCHAR(32)	,
VERSION	    INTEGER	    NOT NULL
);

ALTER TABLE TBL_AA_APP
  ADD PRIMARY KEY ( APP_ID );

ALTER TABLE TBL_AA_APP
  ADD UNIQUE (APP_CODE);  
  
CREATE TABLE TBL_AA_APP_PARAM (
PARAM_ID	  VARCHAR(32)	 NOT NULL,
APP_ID	    VARCHAR(32)	 NOT NULL,
PARAM_NAME	VARCHAR(255) NOT NULL,
PARAM_VALUE	VARCHAR(255) NOT NULL,
CREATED_DT	TIMESTAMP	   NOT NULL,
CREATED_BY	VARCHAR(32)	 NOT NULL,
UPDATED_DT	TIMESTAMP	   ,
UPDATED_BY	VARCHAR(32)	 ,
VERSION	    INTEGER     NOT NULL
);

ALTER TABLE TBL_AA_APP_PARAM
  ADD PRIMARY KEY ( PARAM_ID );
 
ALTER TABLE TBL_AA_APP_PARAM
	ADD FOREIGN KEY (APP_ID) REFERENCES TBL_AA_APP (APP_ID);

CREATE TABLE TBL_AA_SUBJECT (
    SUBJECT_ID            VARCHAR(32)  NOT NULL,
    FIRST_NAME            VARCHAR(100) NOT NULL,
    LAST_NAME             VARCHAR(100),
    EMAIL                 VARCHAR(200),
    PHONE_NUM                 VARCHAR(20),
    EFFECTIVE_DT          DATE,
    EXPIRY_DT             DATE,
    STATUS                VARCHAR(1) NOT NULL,
    LOGICAL_DEL           INTEGER,
    LAST_LOGIN_DT         TIMESTAMP,
    LAST_LOGIN_IP         VARCHAR(20),
    CREATED_DT            TIMESTAMP,
    CREATED_BY            VARCHAR(32),
    UPDATED_DT            TIMESTAMP      ,
    UPDATED_BY            VARCHAR(32)    ,
    VERSION               INTEGER NOT NULL
);

ALTER TABLE TBL_AA_SUBJECT
  ADD PRIMARY KEY ( SUBJECT_ID );

CREATE TABLE TBL_AA_SUBJECT_LOGIN (
    SUBJECT_ID             VARCHAR(32) NOT NULL,
    LOGIN_MECHANISM        VARCHAR(32) NOT NULL,
    LOGIN_NAME             VARCHAR(15) NOT NULL,
    PASSWORD               VARCHAR(2000),
    RECALL_QUESTION        VARCHAR(100),
    RECALL_ANS             VARCHAR(500),
    PASSWORD_CHANGED_DATE  TIMESTAMP,
    ATTEMPTS_MADE          INTEGER,
    CREATED_DT             TIMESTAMP,
    CREATED_BY             VARCHAR(32),
    UPDATED_DT             TIMESTAMP    ,
    UPDATED_BY             VARCHAR(32)  ,
    VERSION                INTEGER NOT NULL,
    FOREIGN KEY (SUBJECT_ID) REFERENCES TBL_AA_SUBJECT (SUBJECT_ID)
);

ALTER TABLE TBL_AA_SUBJECT_LOGIN
    ADD PRIMARY KEY ( SUBJECT_ID, LOGIN_MECHANISM );

CREATE TABLE TBL_AA_LOGIN_LOG (
LOGIN_LOG_ID  VARCHAR(32) NOT NULL,
LOGIN_ID      VARCHAR(15),
APP_CODE      VARCHAR(32) NOT NULL,
LOGIN_TYPE    VARCHAR(20),
LOGIN_STATUS  VARCHAR(100),
CREATED_DT    TIMESTAMP,
LOGIN_IP      VARCHAR(20)
);

ALTER TABLE TBL_AA_LOGIN_LOG
  ADD PRIMARY KEY ( LOGIN_LOG_ID );

CREATE TABLE TBL_AA_SUBJECT_PWD_HISTORY (
OLD_PASSWORD_ID  VARCHAR(32) NOT NULL,
SUBJECT_ID       VARCHAR(32) NOT NULL,
OLD_PASSWORD     VARCHAR(2000) NOT NULL,
CREATED_DT       TIMESTAMP,
FOREIGN KEY (SUBJECT_ID) REFERENCES TBL_AA_SUBJECT (SUBJECT_ID)
);

ALTER TABLE TBL_AA_SUBJECT_PWD_HISTORY
  ADD PRIMARY KEY ( OLD_PASSWORD_ID );

CREATE TABLE TBL_AA_GROUP (
GROUP_ID         VARCHAR(32) NOT NULL,
APP_ID		 			 VARCHAR(32) NOT NULL,
GROUP_NAME       VARCHAR(50) NOT NULL,
GROUP_LABEL      VARCHAR(50),
GROUP_PARENT_ID  VARCHAR(32),
GROUP_TYPE       VARCHAR(32),
LEFT_INDEX       INTEGER,
RIGHT_INDEX      INTEGER,
CREATED_DT       TIMESTAMP,
CREATED_BY       VARCHAR(32),
UPDATED_DT       TIMESTAMP    ,
UPDATED_BY       VARCHAR(32)  ,
VERSION          INTEGER NOT NULL
);

ALTER TABLE TBL_AA_GROUP
    ADD PRIMARY KEY ( GROUP_ID );

ALTER TABLE TBL_AA_GROUP
    ADD FOREIGN KEY (GROUP_PARENT_ID) REFERENCES TBL_AA_GROUP (GROUP_ID);
    
ALTER TABLE TBL_AA_GROUP    
    ADD FOREIGN KEY (APP_ID) REFERENCES TBL_AA_APP (APP_ID);

CREATE TABLE TBL_AA_RESOURCES (
    RESOURCES_ID       VARCHAR(32) NOT NULL,
    APP_ID	       	   VARCHAR(32) NOT NULL,
    RESOURCE_NAME      VARCHAR(100) NOT NULL,
    RESOURCE_PATH      VARCHAR(100),
    RESOURCE_TYPE      VARCHAR(50) NOT NULL,
    REQ_LOGIN_TYPE 		 VARCHAR(11),
    BELONG_TO          VARCHAR(32) NOT NULL,
    LOG_ENABLED        INTEGER NOT NULL ,
    LOG_TRANSACTION    INTEGER NOT NULL ,
    EFFECTIVE_FROM     DATE,
    EFFECTIVE_TO       DATE,
    CREATED_DT         TIMESTAMP,
    CREATED_BY         VARCHAR(32),
    UPDATED_DT         TIMESTAMP   ,
    UPDATED_BY         VARCHAR(32) ,
    VERSION            INTEGER NOT NULL 
);

ALTER TABLE TBL_AA_RESOURCES
  ADD PRIMARY KEY ( RESOURCES_ID );
  
ALTER TABLE TBL_AA_RESOURCES  
  ADD FOREIGN KEY (APP_ID) REFERENCES TBL_AA_APP (APP_ID);

CREATE TABLE TBL_AA_USER_SESSION_INFO (
    JSESSIONID  VARCHAR(128) NOT NULL,
    SUBJECT_ID  VARCHAR(32),
    APP_CODE	VARCHAR(32) NOT NULL,
    LOGIN_ID    VARCHAR(15),
    LOGIN_TYPE  VARCHAR(40),
    FIRST_NAME  VARCHAR(100),
    LAST_NAME   VARCHAR(100),
    IP_ADDRESS  VARCHAR(20),
    UPDATED_DT  TIMESTAMP
);

ALTER TABLE TBL_AA_USER_SESSION_INFO
  ADD PRIMARY KEY ( JSESSIONID );

CREATE TABLE TBL_AA_AUTHORITY (
AUTHORITY_ID  	VARCHAR(32) 	NOT NULL,
AUTHORITY    		VARCHAR(50) 	NOT NULL,
CREATED_DT 			TIMESTAMP           ,
CREATED_BY  		VARCHAR(32)         ,
UPDATED_DT  		TIMESTAMP        ,
UPDATED_BY  		VARCHAR(32)     ,
VERSION     		INTEGER             ,
PRIMARY KEY (AUTHORITY_ID)
);

CREATE TABLE TBL_AA_AUTH2GROUP (
AUTHORITY_ID	VARCHAR(32) NOT NULL,
GROUP_ID			VARCHAR(32) NOT NULL,
CREATED_DT  	TIMESTAMP           ,
CREATED_BY  	VARCHAR(32)        ,
PRIMARY KEY (AUTHORITY_ID, GROUP_ID),
FOREIGN KEY (AUTHORITY_ID) REFERENCES TBL_AA_AUTHORITY (AUTHORITY_ID),
FOREIGN KEY (GROUP_ID) REFERENCES TBL_AA_GROUP (GROUP_ID)
);

CREATE TABLE TBL_AA_SUBJECT2GROUP (
    SUBJECT_ID  VARCHAR(32) NOT NULL,
    GROUP_ID    VARCHAR(32) NOT NULL,
    AUTHORITY_ID	VARCHAR(32),
    CREATED_DT  TIMESTAMP,
    CREATED_BY  VARCHAR(32),
    UPDATED_DT  TIMESTAMP   ,
    UPDATED_BY  VARCHAR(32) ,
    VERSION     INTEGER			NOT NULL,
    PRIMARY KEY (SUBJECT_ID, GROUP_ID),
    FOREIGN KEY (SUBJECT_ID) REFERENCES TBL_AA_SUBJECT (SUBJECT_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES TBL_AA_GROUP (GROUP_ID)
);

CREATE TABLE TBL_AA_GROUP2RES (
    GROUP_ID       VARCHAR(32) NOT NULL,
    RESOURCES_ID   VARCHAR(32) NOT NULL,
    AUTHORITY_ID	VARCHAR(32),
    READ_ACCESS    VARCHAR(1),
    CREATE_ACCESS  VARCHAR(1),
    UPDATE_ACCESS  VARCHAR(1),
    DELETE_ACCESS  VARCHAR(1),
    EFFECTIVE_DT   DATE,
    EXPIRY_DT      DATE,
    CREATED_DT     TIMESTAMP,
    CREATED_BY     VARCHAR(32),
    UPDATED_DT     TIMESTAMP   ,
    UPDATED_BY     VARCHAR(32) ,
    VERSION        INTEGER,
    REF_GROUP_ID   VARCHAR(32),
    PRIMARY KEY (GROUP_ID, RESOURCES_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES TBL_AA_GROUP (GROUP_ID) ,
    FOREIGN KEY (RESOURCES_ID) REFERENCES TBL_AA_RESOURCES (RESOURCES_ID)
);

CREATE TABLE TBL_AA_SUBJECT2RES (
    SUBJECT_ID     VARCHAR(32) NOT NULL,
    RESOURCES_ID   VARCHAR(32) NOT NULL,
    READ_ACCESS    VARCHAR(1),
    CREATE_ACCESS  VARCHAR(1),
    UPDATE_ACCESS  VARCHAR(1),
    DELETE_ACCESS  VARCHAR(1),
    EFFECTIVE_DT   DATE,
    EXPIRY_DT      DATE,
    CREATED_DT     TIMESTAMP,
    CREATED_BY     VARCHAR(32),
    UPDATED_DT     TIMESTAMP   ,
    UPDATED_BY     VARCHAR(32) ,
    VERSION        INTEGER,
    REF_GROUP_ID   VARCHAR(32) ,
    PRIMARY KEY (SUBJECT_ID, RESOURCES_ID),
    FOREIGN KEY (SUBJECT_ID) REFERENCES TBL_AA_SUBJECT (SUBJECT_ID) ,
    FOREIGN KEY (RESOURCES_ID) REFERENCES TBL_AA_RESOURCES (RESOURCES_ID)
);

CREATE TABLE TBL_AA_RES2RES (
    RESOURCES_ID   VARCHAR(32) NOT NULL,
    PARENT_RES_ID  VARCHAR(32) NOT NULL,
    CREATE_ACCESS  VARCHAR(1),
    READ_ACCESS    VARCHAR(1),
    UPDATE_ACCESS  VARCHAR(1),
    DELETE_ACCESS  VARCHAR(1),
    EFFECTIVE_DT   DATE,
    EXPIRY_DT      DATE,
    CREATED_DT     TIMESTAMP,
    CREATED_BY     VARCHAR(32),
    UPDATED_DT     TIMESTAMP   ,
    UPDATED_BY     VARCHAR(32) ,
    VERSION        INTEGER,
    REF_GROUP_ID   VARCHAR(32),
    PRIMARY KEY (RESOURCES_ID, PARENT_RES_ID),
    FOREIGN KEY (RESOURCES_ID) REFERENCES TBL_AA_RESOURCES (RESOURCES_ID),
    FOREIGN KEY (PARENT_RES_ID) REFERENCES TBL_AA_RESOURCES (RESOURCES_ID)
);


CREATE TABLE TBL_AA_GROUP_ADMIN (
    GROUP_ID      VARCHAR(32) NOT NULL,
    ADMIN_TYPE    VARCHAR(1) NOT NULL,
    ADMIN_ID      VARCHAR(32) NOT NULL,
    DELEGATOR_ID  VARCHAR(32),
    PRECEDENCE    INTEGER,
    CREATED_DT    TIMESTAMP,
    CREATED_BY    VARCHAR(32),
    UPDATED_DT    TIMESTAMP   ,
    UPDATED_BY    VARCHAR(32) ,
    VERSION       INTEGER NOT NULL,
    PRIMARY KEY (GROUP_ID, ADMIN_TYPE, ADMIN_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES TBL_AA_GROUP (GROUP_ID),
    FOREIGN KEY (ADMIN_ID) REFERENCES TBL_AA_SUBJECT (SUBJECT_ID) ,
		FOREIGN KEY (DELEGATOR_ID) REFERENCES TBL_AA_SUBJECT (SUBJECT_ID)
);

CREATE TABLE TBL_AA_SUBJECT2DELEGATOR (
    SUBJECT2DELEGATOR_PK    VARCHAR(32) NOT NULL,
    SUBJECT_ID                VARCHAR(32) NOT NULL,
    DELEGATOR_ID              VARCHAR(32) NOT NULL,
    CREATED_DT                TIMESTAMP,
    CREATED_BY                VARCHAR(32),
    VERSION                   INTEGER NOT NULL,
    PRIMARY KEY (SUBJECT2DELEGATOR_PK),
    FOREIGN KEY (SUBJECT_ID) REFERENCES TBL_AA_SUBJECT (SUBJECT_ID),
    FOREIGN KEY (DELEGATOR_ID) REFERENCES TBL_AA_SUBJECT (SUBJECT_ID)
);

CREATE TABLE TBL_AA_DELEGATED_RESOURCES (
    SUBJECT2DELEGATOR_PK      VARCHAR(32) NOT NULL,
    RESOURCES_ID               VARCHAR(32) NOT NULL,
    READ_ACCESS                VARCHAR(1),
    CREATE_ACCESS              VARCHAR(1),
    UPDATE_ACCESS              VARCHAR(1),
    DELETE_ACCESS              VARCHAR(1),
    EFFECTIVE_DT               DATE,
    EXPIRY_DT                  DATE,
    CREATED_DT                 TIMESTAMP,
    CREATED_BY                 VARCHAR(32),
    UPDATED_DT                 TIMESTAMP   ,
    UPDATED_BY                 VARCHAR(32) ,
    VERSION                    INTEGER,
    REF_GROUP_ID   VARCHAR(32),
    PRIMARY KEY (SUBJECT2DELEGATOR_PK, RESOURCES_ID),
    FOREIGN KEY (SUBJECT2DELEGATOR_PK) REFERENCES TBL_AA_SUBJECT2DELEGATOR (SUBJECT2DELEGATOR_PK) ,
    FOREIGN KEY (RESOURCES_ID) REFERENCES TBL_AA_RESOURCES (RESOURCES_ID)
);

CREATE TABLE TBL_AA_PUBLIC_REG
(
  SUBJECT_ID               VARCHAR(32) NOT NULL,
  LOGIN_MECHANISM           VARCHAR(32) NOT NULL,
  PUBLIC_ACTIVATION_KEY    VARCHAR(32),
  REASON                   VARCHAR(200),
  UPDATED_DT               TIMESTAMP   
);
ALTER TABLE TBL_AA_PUBLIC_REG
    ADD PRIMARY KEY (SUBJECT_ID, LOGIN_MECHANISM);

CREATE TABLE TBL_AA_SIGN_LOG
(
    SIGN_LOG_ID     VARCHAR(32)  NOT NULL,
    REQUEST_URI     VARCHAR(255) NOT NULL,
    IP_ADDRESS      VARCHAR(40)  NOT NULL,
    DETAILS         BINARY         NOT NULL,
    CREATED_DT      TIMESTAMP    NOT NULL,
    CREATED_BY      VARCHAR(32)  NOT NULL,
    VALID           CHAR(1)      NOT NULL,
    PRIMARY KEY (SIGN_LOG_ID)
);

CREATE TABLE TBL_AA_RSA	(
	RSA_ID           VARCHAR(32)	NOT NULL,
	KEY_PAIR	       BINARY,
	PRIMARY KEY (RSA_ID)
);

insert into TBL_AA_APP values('IConnect','IConnect','IConnect','IConnect',CURRENT_TIMESTAMP,'SYSTEM',CURRENT_TIMESTAMP,'SYSTEM',0);
insert into TBL_AA_SUBJECT values('1','iconnect','','sample_user@ncs.com.sg',null,null,null,'A',0,null,null,null,null,null,null,1);
insert into TBL_AA_SUBJECT_LOGIN values ('1','PASSWORD','user1','vFR3ULknl/lVs2ESzJvdXN330IYhUdA6FnraiZWqJKmtJGELNqaLwC2iQUHuUWcK6hPtZGkJmkRT8zXLI5212g==','AAA','z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,'SYSTEM',CURRENT_TIMESTAMP,'SYSTEM',1);
insert into TBL_AA_GROUP values('REQ-group-universal','IConnect','UNIVERSAL_GROUP',null,null,null,1,1,'2012-01-01 00:00:00','DEF-user-appadmin','2011-02-01 00:00:00','DEF-user-appadmin',1);
insert into TBL_AA_SUBJECT2GROUP values('1','REQ-group-universal','NA',now(),'SYSTEM',now(),'SYSTEM',1);